version: "3"
services:
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    ports:
      - "8080:8080"
    environment:
      LIBSQL_SERVER_HTTP_PORT: 8080
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/libsql
    networks:
      - app-network
  app:
    image: docker.io/kampouse/justchat-linux:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
      - "4983:4983"
    env_file:
      - .env
    environment:
      DATABASE_URL: http://db:8080
    depends_on:
      - db
    networks:
      - app-network
volumes:
  db-data:
    driver: local
networks:
  app-network:
    driver: bridge
